### ISSUE TITLE
Support headings

### ISSUE THREAD

**Issue by PeterJCLaw** [Mr0grog/google-docs-to-markdown#16]
Thanks for creating this tool.
Whenever I paste any content which has headings in it, I don't get any Markdown output.

In the JS console I do get a `TypeError: n is undefined`, however I'm not sure if that's related.

**Comment by Mr0grog** [comment]
Hmmmm, I’m not able to reproduce this. Can you link to a public Google Doc that demonstrates the issue, and post what browser and operating system you are using?

Additionally, are you running this locally or using the published version at https://bafybeierebjekxfpuut3x7m4kzdrf3qlmaulr5mb4euq5knbw5g7aaq36y.ipfs.dweb.link/ ?

**Comment by PeterJCLaw** [comment]
I'm using the published hosted version. I'm using Firefox on Ubuntu 20.04.1.

Hrm, I've just managed to make headings work for a fresh doc.

I have managed to cut-down a doc which reproduces the issue though: https://docs.google.com/document/d/1B-0eG3zQrVKOdYGaqyE2C-ePrC1zFedQFqhGm6neKtA/edit

**Comment by PeterJCLaw** [comment]
I've had a play with this locally. I think the issue is that `removeLineBreaksBeforeBlocks` calls `isBlock` with a null value, but `isBlock` can't cope with that. The fix is to change the `isBlock` function:
```diff
$ git di | cat
diff --git a/lib/fix-google-html.js b/lib/fix-google-html.js
index 0b680db..48cf85b 100644
--- a/lib/fix-google-html.js
+++ b/lib/fix-google-html.js
@@ -49,7 +49,7 @@ const blockElements = new Set([
 
 const isList = node => node.tagName === 'ul' || node.tagName === 'ol';
 const isStyled = node => node.type === 'element' && node.properties.style;
-const isBlock = node => blockElements.has(node.tagName);
+const isBlock = node => node && blockElements.has(node.tagName);
 
 // Wrap the children of `node` with the `wrapper` node.
 function wrapChildren (node, wrapper) {
```

Not sure if that would have any side effects though. Do you have any tests I should run to check this fix?

**Comment by Mr0grog** [comment]
Hey, sorry I’ve been super slow to respond here, and thanks for digging into this!

It seems like the trigger for this is that it’s possible to make a Google doc where the last node in an element (like a list item or the whole doc, both of which are the case in your example) is a `<br>`. Somehow, I don’t think I’d seen that before.

The fix you’re proposing makes sense to me, and I don’t think it should have any problematic side effects. Worst case, we might find that we want to do the opposite and cause these line breaks at the end of a block’s content to be removed (your change would preserve them), but I think that’s probably an aesthetic rather than functional issue. It shouldn’t create broken Markdown either way.

Feel free to submit a PR, otherwise I’ll try to get to it this weekend.

> Do you have any tests I should run to check this fix?

Unfortunately, no. 😞 I originally wrote this as a quick afternoon hack, and never got around to writing a good series of tests. If you’d like to add some, that’d be fantastic.

**Comment by PeterJCLaw** [comment]
I had a very quick look at adding some tests using [`jest`](https://jestjs.io/), but hit a syntax error (in the test file) which didn't make any sense to me. Unfortunately I'm not much of a JS person so I've given up. Anyway #20 hopefully resolves this.

**Comment by Mr0grog** [comment]
No worries! #20 looked good and I’ve merged it in. 😄
