### ISSUE TITLE
Superscripts turn into non superscript

### ISSUE THREAD

**Issue by abrambailey** [Mr0grog/google-docs-to-markdown#33]
Expected behavior would be paste superscript, get superscript, but ² turns into 2 in the results.

**Comment by Mr0grog** [comment]
Good catch! Just tried this out and I see what you mean.

I’m not sure I’ll get to this before the weekend, but will definitely get this fixed. In the mean time, pull requests are also welcome. :)

---

Looks like this is happening because Google Docs renders HTML like:

```html
<span>Test document</span><span><span style="font-size:0.6em;vertical-align:super;">2</span></span>
```

^ where the “2” is superscripted. The key part is `vertical-align: super;` in the style attribute. Ditto for subscripts but with `vertical-align:sub;`.

The best fix here probably to expand `unInlineStyles()` or add a similar transform that converts the `span` above into a `sup` or `sub` element as appropriate: https://github.com/Mr0grog/google-docs-to-markdown/blob/8fdaadd76212e257c30c73052c3ff654d8d46fb3/lib/fix-google-html.js#L103-L120

There may also need to be some special handling of those elements in the `rehype2remark` steps, too; not sure.

**Comment by Mr0grog** [comment]
@abrambailey this should be fixed now! If you are using https://mr0grog.github.io/google-docs-to-markdown/ things should just work, and if you are using a web3-style link, you should switch to https://bafybeihpbbnpk5f2cze5osp4su5hg52jplz7njwgl6nbqlqinlhwbu4imm.ipfs.dweb.link/ :)

**Comment by abrambailey** [comment]
Amazing. Thank you!!!
