### ISSUE TITLE
Code blocks addon support

### ISSUE THREAD

**Issue by jothikannan89** [Mr0grog/google-docs-to-markdown#81]
Hi,

I have been using this to convert my google docs to mdx, everything works like chars, thanks for this awesome project.

Now, I would like to introduce code blocks(not inline code), using addons or with three backticks(```).  is it possible to do?

example

```
```for i in range(5):
       print("Hello")
```
```

**Comment by jothikannan89** [comment]
It seems 4 space indent is no more supported with mdx2

![image](https://github.com/Mr0grog/google-docs-to-markdown/assets/28098883/da7c4152-e953-43e4-9ac4-19770fdfc68e)

**Comment by Mr0grog** [comment]
> It seems 4 space indent is no more supported with mdx2

Ah, if you are using MDX, you have to keep in mind that [it is not Markdown](https://github.com/micromark/mdx-state-machine#72-deviations-from-markdown); it’s just *very similar* to Markdown. It doesn’t support indentation for code, autolinking, comments, unescaped curly brackets, etc. There are a lot of things this tool might output that don’t work in MDX.

Like I said earlier, I’d be very happy to accept a PR here that adds options people can set (e.g. for fenced code blocks, or other features to get MDX-compatible output). That’s just not a *small or simple* change, since adding options means also adding a UI to set the options.

**Comment by Mr0grog** [comment]
I recently added code fences as an option (see #217), which should solve the specific issue here. That said, there are a variety of other idiosyncrasies with MDX, so your mileage may vary.

For now, I’m considering this issue solved. Please comment if you’re running into other problems!
