### ISSUE TITLE
Code blocks sometimes interpreted as singly quoted words

### ISSUE THREAD

**Issue by mkmik** [Mr0grog/google-docs-to-markdown#93]
I have a doc with two seemingly identical blocks:

```
foo bar
```

https://docs.google.com/document/d/1HR8-NSaiNEO0sfQYZ0Lg2NDXgHuofNk--qxsfm1P9bk/view

When I paste that doc in https://gdoc2md.com/ I get:

```markdown
This correctly converts to a block:

    foo bar

This instead produces individually quoted words:

`foo` `bar`
```

_Something_ in the code block content makes the difference.

**Comment by Mr0grog** [comment]
Interesting! It's very subtle, but in the second block, the space between the two words has been formatted to use Arial as the font instead of Roboto Mono. I didn't even realize you could do that with the code blocks feature in Google Docs.

So what's happening here is that, when you copy/paste from a Google Doc, it loses information about code blocks. We detect that something was probably a block by looking for lines that are all monospaced (relevant code: [convert monospaced to code](https://github.com/Mr0grog/google-docs-to-markdown/blob/9b045ab7b6cb1f283191f4095e120172d76dd5d1/lib/fix-google-html.js#L171-L175), then later [looking for lines that are all code](https://github.com/Mr0grog/google-docs-to-markdown/blob/9b045ab7b6cb1f283191f4095e120172d76dd5d1/lib/fix-google-html.js#L414-L510)) since we can't actually see if it was a "code block" object from Google Docs. In other words, we look for something like this in HTML:

```html
<p><span style="font-family: monospace;">foo bar</span></p>
```

Since the second block in this doc has a non-monospaced bit of text in the middle, it comes through as a line with mixed mono and non-mono text, and we interpret it as a paragraph with some normal text and some inline mono, or code. E.g. we see something like this in the doc:

```html
<p>
  <span style="font-family: monospace;">foo</span>
  <span style="font-family: Arial;"> </span>
  <span style="font-family: monospace;">bar</span>
</p>
```

I think we could potentially work around this by ignoring the formatting of space characters when detecting code blocks, but you'd still run into a similar problem if you formatted some _text_ differently in the code block.

---

An aside: when you copy from a Google Doc, it puts 3 different versions of the text you copied on your clipboard. Plain text for basic text editors to use, HTML for other applications that understand rich formatting, and a special in-memory format for pasting back into that or another Google Doc and that is different from how a doc looks in Google's APIs. We use the HTML because it's meant for third-party tools and because I’m a little worried about both the stability and complexity of the third format. But the HTML version is a little lossy in terms of how it represents things, leading to stuff like this.
