### ISSUE TITLE
Link within the document

### ISSUE THREAD

**Issue by trustedtomato** [Mr0grog/google-docs-to-markdown#95]
It would be nice if you could support linking with the document.
Example:
https://docs.google.com/document/d/1AeGd3Zn2Aab0X1bHHF-vbTbSNPKrZHfw_Woax3YsYXg/edit

Seems like the heading ID is random, so we could just check if the ID linked anchor exists in the document, and if so, replace the link with the relevant `encodeURIComponent(heading.textContent)` .

I can make a PR if that's fine. (Some pointers would be appreciated.)

**Comment by Mr0grog** [comment]
Unfortunately, the linked anchor *doesn't* ever exist in the document. 😞  (Well, it doesn't exist in the HTML Google Docs puts on the pasteboard, but it does exist in *exported* HTML, but we don't really support exported HTML yet; see #60.)

If you see another way to do this, great! I'd be happy to take a PR, not having support for this has been pretty annoying.

---

As for where to make your changes, you'd probably want to add a function to [`lib/fix-google-html.js`](https://github.com/Mr0grog/google-docs-to-markdown/blob/main/lib/fix-google-html.js) and then call it from the `fixGoogleHtml()` function (at the bottom of that file).

And of course add a test, ideally from an actual Google Doc fixture — once you’ve made the doc, add it to the list of fixtures in `scripts/download-fixtures.js`: https://github.com/Mr0grog/google-docs-to-markdown/blob/50fd3e1005c20bf65e5aee4bfca190323753e9b1/scripts/download-fixtures.js#L11-L20

…then run `npm run download-fixtures` to download the doc as a fixture; add an expected result to `test/fixtures/<name-of-doc>.expected.md` and add an reference to the fixture in `test/unit/convert.test.js` (this part should really just find and run all the fixtures so you don't have to add it manually, but I just haven't done that yet): https://github.com/Mr0grog/google-docs-to-markdown/blob/50fd3e1005c20bf65e5aee4bfca190323753e9b1/test/unit/convert.test.js#L17-L20

---

FWIW, I have previously thought about parsing Google Docs's internal pasteboard format (it puts 3 items on the pasteboard — a plain text version, an HTML version (which we use because it's sort of standard and easy-ish to handle), and an internal, JSON-based format (which I've avoided because it's more complex and I’m not sure it's particularly stable)) to get this kind of data. That version has all the info you need to put the link and the header (or bookmark) together and do the right thing (plus stuff that would be helpful for lots of other features!).

There might be a way to pull the link/target data out of that and match it to the HTML tree we are working with, but I fear that will be pretty complex.

**Comment by trustedtomato** [comment]
You're right, the anchor is skipped :thinking: That definitely causes trouble.
I looked into the internal format, and actually, mapping the HTML headings to the internal representation of the headings is not too bad.

First, let's save the clipboard data to a global variable `x` so that we can work with it: 
```javascript
addEventListener('paste', event => {
	event.preventDefault()
	x = event.clipboardData.getData(event.clipboardData.types[0])
})
```

Now try running this in the console:
```javascript
JSON.parse(JSON.parse(x).data)
  .resolved
  .dsl_styleslices
  .find(styleslice => styleslice.stsl_type === 'paragraph')
  .stsl_styles
  .filter(style => style?.ps_hdid)
  .map(heading => ({ level: heading.ps_hd, id: heading.ps_hdid })) 
```

This yields us:
```json
[
  {
    "level": 1,
    "id": "h.pamex66muyvg"
  },
  {
    "level": 1,
    "id": "h.eealtyj7rqvp"
  },
  {
    "level": 2,
    "id": "h.9a9xaev2gy02"
  },
  {
    "level": 2,
    "id": "h.n8whxpalwger"
  },
  {
    "level": 3,
    "id": "h.gu3qhruz893g"
  },
  {
    "level": 3,
    "id": "h.k1400r9il2zk"
  },
  {
    "level": 1,
    "id": "h.a6iu1pkdnp98"
  },
  {
    "level": 2,
    "id": "h.r0a4q0cth4ct"
  },
  {
    "level": 2,
    "id": "h.v82m9mnuowlw"
  },
  {
    "level": 2,
    "id": "h.7z1ie74bl28q"
  },
  {
    "level": 1,
    "id": "h.etkc1o6izye"
  }
]
```

Which maps to the respective h* elements one-to-one.

**Comment by trustedtomato** [comment]
It is hacky though, and depends on the internal format, which is supposably more prone to change than the HTML.
However, if we double check that the mapping looks okay, then I don't think this is gonna cause any trouble.

So, if the mapping is fine, we can just loop over the links, find each docs.google.com URL, and if the #heading matches, we can replace the URL with `'#' + encodeURIComponent(heading.textContent)`

**Comment by trustedtomato** [comment]
Or maybe just `'#h-' + indexOfTheHeading`. In the case of `h.k1400r9il2zk` from [my previous comment](https://github.com/Mr0grog/google-docs-to-markdown/issues/95#issuecomment-1741377122), that would be `#h-5`.
This would also work in the cases when multiple headers contain the same text.
What do you think, how should we generate the ID for the headings?

---

One more question: what do you think, how should we put the ID to the heading?
1. There's this syntax: `# heading {#custom-id}`, but I'm not sure how much that's supported.
2. We could resort to HTML here: `<h1 id="custom-id">heading</h1>`. Not elegant, but might be more supported than the special markdown syntax.
3. We could just rely on the user to post-process the Markdown correctly. Would be an ugly solution.
4. Some other solution?

**Comment by Mr0grog** [comment]
Ah, nice, if they are reliably in order like that it's pretty straightforward! I was thinking you would have to do the work of mapping the IDs to locations in the text, and map that somehow to the DOM.

Did you check to see whether bookmarks are similarly easy to handle?

>> So, if the mapping is fine, we can just loop over the links, find each docs.google.com URL, and if the #heading matches, we can replace the URL with `'#' + encodeURIComponent(heading.textContent)`
>
> Or maybe just `'#h-' + indexOfTheHeading`. In the case of `h.k1400r9il2zk` from [my previous comment](https://github.com/Mr0grog/google-docs-to-markdown/issues/95#issuecomment-1741377122), that would be `#h-5`.
> This would also work in the cases when multiple headers contain the same text.

Yeah, we'd need to do at least something for headings that might happen to have duplicate text. The easiest thing is probably your suggestion: `#h-<index>`. It might be slightly nicer from a *user* perspective if it was `#h-<lower-case-and-replace-spaces-with-dashes>-<index-if-there-are-duplicate-text-headings>`, which matches how a lot of other Markdown tools handle linkable headings (e.g. this is basically how GitHub does it) so it will, in many cases, just work. But that requires a lot more book-keeping work. Either way is fine with me.

> One more question: what do you think, how should we put the ID to the heading?

I think the different naming I suggested above will make it *just work* for a lot of use cases. But the `# heading {#custom-id}` syntax is neat! That’s new to me.

The approach I've seen a lot is to just throw an empty anchor at the end of the heading (or sometimes at the start):

```markdown
# heading <a id="custom-id"></a>
```

I don't have a particularly strong opinion on any of those. The last one will always work, so I probably lean towards it because it's reliable. But it is definitely the ugliest of possible options. 🤷

**Comment by trustedtomato** [comment]
I checked now, bookmarks are also in order. We don't really have a way to know where the bookmarks are though, so here, we need to map the bookmark array to the characters in the document.
Assuming we have variable x from here https://github.com/Mr0grog/google-docs-to-markdown/issues/95#issuecomment-1741377122, 
```javascript
y = JSON.parse(JSON.parse(x).data);
y.resolved.dsl_spacers.split("").map((char, index) => {
  bookmark = y.resolved.dsl_entitypositionmap.bookmark[index]
  if (!bookmark) {
    return char
  } else {
    return `<span id="${bookmark}"></span>${char}`
  }
})
  .join("");
```
yields
```
Hello World.
Link to the first heading.
Hello World.
Link to the first bookmark.
Hello World.
Link to the second bookmark.
Hello World.
First heading
Hello World.
<span id="id.qbdatvy5x87"></span>First bookmark.
Second heading
Hello World.
Third heading
Hello World.
<span id="id.gg8i29488moj"></span>Second bookmark.
Fourth heading
Hello World.
```

---

OK, `# heading <span id="custom-id"></span>` is fine by me as well, I agree that that's probably the most reliable one.
And the `#h-<lower-case-and-replace-spaces-with-dashes>-<index-if-there-are-duplicate-text-headings>` also seems fine to me. Do you know some library which could handle this? Would be nice if we didn't have to handle non-latin stuff like áéüű or 漢字. Otherwise, we can do `#h-encodeURIComponent(<lower-case-and-replace-spaces-with-dashes>-<index-if-there-are-duplicate-text-headings>)`.

**Comment by trustedtomato** [comment]
Maybe this one?
https://www.npmjs.com/package/github-slugger

**Comment by trustedtomato** [comment]
OK, I think the PR is ready now for a review :slightly_smiling_face:
